import type { OrderModel } from "@/models/orders/order-model";

export const NEW_ORDER_EMPTY: OrderModel = {
  id: "",
  customerId: 0,
  createdAt: new Date(),
  representativeId: 0,
  carrierId: 0,
  deliveryLocationId: "",
  discountPercentual: 0,
  integrationMessage: "",
  paymentConditionId: 0,
  grossTotalValue: 0,
  netTotalValue: 0,
  statusId: 0,
  whatAppPhoneNumber: "",
  priceTableId: "",
  branchId: "",
  items: [],
  isBudget: false,
  fiscalClassificationId: "",
  isCompleted: false,
  comments: "",
};

export const NEW_BUDGET_EMPTY: OrderModel = {
  id: "",
  customerId: 0,
  createdAt: new Date(),
  representativeId: 0,
  carrierId: 0,
  deliveryLocationId: "",
  discountPercentual: 0,
  integrationMessage: "",
  paymentConditionId: 0,
  grossTotalValue: 0,
  netTotalValue: 0,
  statusId: 0,
  whatAppPhoneNumber: "",
  priceTableId: "",
  branchId: "",
  items: [],
  isBudget: true,
  fiscalClassificationId: "",
  isCompleted: false,
  comments: "",
};
