import { type MenuModel } from "@/models/menu-model";

export const MENU_DATA: MenuModel[] = [
  {
    id: "1",
    title: "Dashboards",
    url: "",
    icon: "HomeIcon",
    isActive: false,
    children: [
      {
        id: "1.2",
        title: "Resumo Geral",
        url: "/dashboard",
        icon: "HomeIcon",
        isActive: false,
        children: [],
      },
      {
        id: "1.3",
        title: "Vendas por Período",
        url: "/dashboards/dashboard1",
        icon: "CircleIcon",
        isActive: false,
        children: [],
      },
      {
        id: "1.4",
        title: "Vendas por Família",
        url: "/dashboards/dashboard2",
        icon: "CircleIcon",
        isActive: false,
        children: [],
      },
      {
        id: "1.5",
        title: "Ano Atual x Anterior",
        url: "/dashboards/dashboard3",
        icon: "CircleIcon",
        isActive: false,
        children: [],
      },
      {
        id: "1.6",
        title: "Vendas por UF",
        url: "/dashboards/dashboard4",
        icon: "CircleIcon",
        isActive: false,
        children: [],
      },
      {
        id: "1.7",
        title: "Partner",
        url: "/dashboards/dashboard5",
        icon: "CircleIcon",
        isActive: false,
        children: [],
      },
      {
        id: "1.8",
        title: "Grupo de Produto",
        url: "/dashboards/dashboard6",
        icon: "CircleIcon",
        isActive: false,
        children: [],
      },
      {
        id: "1.9",
        title: "Ranking Produtos",
        url: "/dashboards/dashboard7",
        icon: "CircleIcon",
        isActive: false,
        children: [],
      },
      {
        id: "1.10",
        title: "Metas x Realizado",
        url: "/dashboards/dashboard8",
        icon: "CircleIcon",
        isActive: false,
        children: [],
      },
      {
        id: "1.11",
        title: "País x Ano",
        url: "/dashboards/dashboard9",
        icon: "CircleIcon",
        isActive: false,
        children: [],
      },
    ],
  },
  {
    id: "1.1",
    title: "Outlet",
    url: "/outlet",
    icon: "ShoppingCart",
    isActive: false,
    children: [],
  },
  {
    id: "2",
    title: "Pedidos",
    url: "/orders",
    icon: "InboxIcon",
    isActive: false,
    children: [],
  },
  {
    id: "3",
    title: "Simulações",
    url: "/budgets",
    icon: "FoldersIcon",
    isActive: false,
    children: [],
  },
  {
    id: "10",
    title: "Confirmação Pedido",
    url: "/order-confirmation",
    icon: "CheckIcon",
    isActive: false,
    children: [],
  },
  {
    id: "4",
    title: "Consultas",
    url: "",
    icon: "SearchIcon",
    isActive: false,
    children: [
      {
        id: "41",
        title: "Estoque Disponível",
        url: "/stock/product-stock",
        icon: "CircleIcon",
        isActive: false,
      },
      {
        id: "42",
        title: "ESLI011",
        url: "/stock/esli011",
        icon: "CircleIcon",
        isActive: false,
      },
    ],
  },
  {
    id: "5",
    title: "Relatórios",
    url: "",
    icon: "PrinterIcon",
    children: [
      {
        id: "51",
        title: "Comissão",
        url: "/reports/comissao",
        icon: "CircleIcon",
      },
      {
        id: "52",
        title: "Lista de Clientes",
        url: "/reports/customers-list",
        icon: "CircleIcon",
      },
      {
        id: "53",
        title: "Lista de Pedidos",
        url: "/reports/lista-pedidos",
        icon: "CircleIcon",
      },
      {
        id: "54",
        title: "Prod. Vendidos Período",
        url: "/reports/prod-vendidos-periodo",
        icon: "CircleIcon",
      },
      {
        id: "55",
        title: "Prod. Vendidos Mensal",
        url: "/reports/prod-vendidos-mensal",
        icon: "CircleIcon",
      },
      {
        id: "56",
        title: "Faturamento Cliente",
        url: "/reports/faturamento-cliente",
        icon: "CircleIcon",
      },
      {
        id: "57",
        title: "Faturamento Fiscal",
        url: "/reports/faturamento-fiscal",
        icon: "CircleIcon",
      },
      {
        id: "58",
        title: "Títulos Financeiros",
        url: "/reports/titulos-financeiros",
        icon: "CircleIcon",
      },
    ],
  },
  {
    id: "6",
    title: "Aprovações",
    url: "/approvals",
    icon: "CircleCheckIcon",
    children: [],
  },
  {
    id: "7",
    title: "Cadastros Gerais",
    url: "",
    icon: "FolderIcon",
    children: [
      {
        id: "71",
        title: "Metas Representantes",
        url: "/registrations/representative-goals",
        icon: "UsersIcon",
      },
      {
        id: "73",
        title: "Alçadas de Aprovação",
        url: "/registrations/approval-levels",
        icon: "CheckCircleIcon",
      },
      {
        id: "74",
        title: "Produtos",
        icon: "BoxIcon",
        url: "/registrations/products",
      },
      {
        id: "741",
        title: "Mensagens SKU",
        icon: "MessageCircleMoreIcon",
        url: "/registrations/sku-messages",
      },
      {
        id: "740",
        title: "Tipo Item",
        icon: "BoxIcon",
        url: "/registrations/item-types",
      },
      {
        id: "76",
        title: "Clientes",
        url: "/registrations/customers",
        icon: "UsersIcon",
      },
      {
        id: "77",
        title: "Cond. de Pagamento",
        url: "/registrations/payment-conditions",
        icon: "DollarSignIcon",
      },
      {
        id: "78",
        title: "Tabelas de Preço",
        url: "/registrations/price-tables",
        icon: "TableIcon",
      },
      {
        id: "75",
        title: "Grupos de Venda",
        url: "/registrations/sales-group",
        icon: "ComponentIcon",
      },
    ],
  },
  {
    id: "8",
    title: "Adm. Aplicativo",
    url: "",
    icon: "SmartphoneIcon",
    children: [
      {
        id: "81",
        title: "Notificações",
        url: "/mobile/notifications",
        icon: "BellIcon",
      },
      {
        id: "82",
        title: "Comunicados",
        url: "/mobile/communications",
        icon: "MessageCircleIcon",
      },
      {
        id: "83",
        title: "Links Úteis",
        url: "/mobile/links",
        icon: "LinkIcon",
      },
    ],
  },
  {
    id: "9",
    title: "Configurações",
    url: "",
    icon: "SettingsIcon",
    children: [
      {
        id: "93",
        title: "Grupos de Usuários",
        url: "/admin/user-groups",
        icon: "FolderTreeIcon",
      },
      {
        id: "91",
        title: "Usuários",
        url: "/admin/users",
        icon: "UsersIcon",
      },
      {
        id: "92",
        title: "Configurações",
        url: "/admin/settings",
        icon: "SettingsIcon",
      },
      {
        id: "93",
        title: "Sincronização",
        url: "/system/sync-status",
        icon: "FolderSyncIcon",
      },
    ],
  },
];
