import type { OrderItemModel } from "./order-item-model";
import type { CustomerModel } from "../registrations/customer.model";
import type { RepresentativeModel } from "../representative.model";
import type { PriceTableModel } from "../registrations/price-table.model";
import type { DeliveryLocationModel } from "../delivery-location.model";
import type { CarrierModel } from "../carrier.model";
import type { PaymentConditionModel } from "../registrations/payment-condition.model";

export type OrderModel = {
  id: string;
  orderId: string;
  erpOrderId: number;
  customerId: number;
  customerAbbreviation: string;
  createdAt: Date;
  statusId: number;
  deliveryLocationId: string;
  integrationMessage: string;
  integratedAt?: Date | null;
  branchId: string;
  discountPercentual: number;
  currencyId: number;
  representativeId: number;
  orderClassificationId: number;
  createdBy: string;
  isParcialBilling: boolean;
  useCustomerCarrier: boolean;
  minBillingDate?: Date | null;
  maxBillingDate?: Date | null;
  paymentConditionId: number;
  isBudget: boolean;
  freightValue: number;
  freightPaymentId: number;
  carrierId: number;
  whatAppPhoneNumber: string;
  comments: string;
  freightPayedValue: number;
  additionalDiscount: number;
  grossTotalValue: number;
  netTotalValue: number;
  creditStatusId: number;
  freightTypeId: number;
  origin: string;
  priceTableId: string;
  priceTypeId: number;
  isCompleted: boolean;
  fiscalClassificationId: string;
  orderRepId: string;

  // Navigation properties
  items: OrderItemModel[];
  customer?: CustomerModel;
  representative?: RepresentativeModel;
  priceTable?: PriceTableModel;
  deliveryLocation?: DeliveryLocationModel;
  carrier?: CarrierModel;
  paymentCondition?: PaymentConditionModel;
};
