import type { ProductModel } from "../product.model";
import type { PriceTableModel } from "../registrations/price-table.model";
import type { OrderItemTaxModel } from "./order-item-tax-model";

export type OrderItemModel = {
  id: string;
  orderId: string;
  productId: string;
  orderQuantity: number;
  inputPrice: number;
  priceTablePrice: number;
  priceTableId: string;
  deliveryDate: Date;
  originalDeliveryDate: Date;
  availability: string;
  referenceCode: string;
  ncm: string;
  sequence: number;
  deliveredQuantity: number;
  allocatedQuantity: number;
  statusId: number;
  comments: string;
  customerAbbreviation: string;
  fiscalClassificationId: string;
  grossItemValue: number;
  netItemValue: number;
  suggestPrice: number;
  costValue: number;
  product: ProductModel;
  taxes: OrderItemTaxModel[];
  priceTable: PriceTableModel;
};
