/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AuthLoginRouteImport } from './pages/auth/login'
import { Route as AppOutletIndexRouteImport } from './pages/_app/outlet/index'
import { Route as AppOrdersIndexRouteImport } from './pages/_app/orders/index'
import { Route as AppDashboardIndexRouteImport } from './pages/_app/dashboard/index'
import { Route as AppBudgetsIndexRouteImport } from './pages/_app/budgets/index'
import { Route as AppApprovalsIndexRouteImport } from './pages/_app/approvals/index'
import { Route as AppOrdersNewOrderRouteImport } from './pages/_app/orders/new-order'
import { Route as AppBudgetsNewBudgetRouteImport } from './pages/_app/budgets/new-budget'
import { Route as AppSystemSyncStatusIndexRouteImport } from './pages/_app/system/sync-status/index'
import { Route as AppStockProductStockIndexRouteImport } from './pages/_app/stock/product-stock/index'
import { Route as AppStockEsli011IndexRouteImport } from './pages/_app/stock/esli011/index'
import { Route as AppReportsDashboardProductGroupsIndexRouteImport } from './pages/_app/reports/dashboard-product-groups/index'
import { Route as AppReportsCustomersListIndexRouteImport } from './pages/_app/reports/customers-list/index'
import { Route as AppReportsComissaoIndexRouteImport } from './pages/_app/reports/comissao/index'
import { Route as AppRegistrationsSalesGroupIndexRouteImport } from './pages/_app/registrations/sales-group/index'
import { Route as AppRegistrationsRepresentativeGoalsIndexRouteImport } from './pages/_app/registrations/representative-goals/index'
import { Route as AppRegistrationsProductsIndexRouteImport } from './pages/_app/registrations/products/index'
import { Route as AppRegistrationsPriceTablesIndexRouteImport } from './pages/_app/registrations/price-tables/index'
import { Route as AppRegistrationsPaymentConditionsIndexRouteImport } from './pages/_app/registrations/payment-conditions/index'
import { Route as AppRegistrationsCustomersIndexRouteImport } from './pages/_app/registrations/customers/index'
import { Route as AppRegistrationsApprovalLevelsIndexRouteImport } from './pages/_app/registrations/approval-levels/index'
import { Route as AppOrdersOrderIdIndexRouteImport } from './pages/_app/orders/$orderId/index'
import { Route as AppMobileNotificationsIndexRouteImport } from './pages/_app/mobile/notifications/index'
import { Route as AppMobileLinksIndexRouteImport } from './pages/_app/mobile/links/index'
import { Route as AppMobileCommunicationsIndexRouteImport } from './pages/_app/mobile/communications/index'
import { Route as AppAdminUsersIndexRouteImport } from './pages/_app/admin/users/index'
import { Route as AppAdminUserGroupsIndexRouteImport } from './pages/_app/admin/user-groups/index'
import { Route as AppAdminSettingsIndexRouteImport } from './pages/_app/admin/settings/index'
import { Route as AppRegistrationsSalesGroupNewGroupRouteImport } from './pages/_app/registrations/sales-group/new-group'
import { Route as AppRegistrationsApprovalLevelsNewLevelRouteImport } from './pages/_app/registrations/approval-levels/new-level'
import { Route as AppMobileLinksNewLinkRouteImport } from './pages/_app/mobile/links/new-link'
import { Route as AppMobileCommunicationsNewCommunicateRouteImport } from './pages/_app/mobile/communications/new-communicate'
import { Route as AppAdminUsersNewUserRouteImport } from './pages/_app/admin/users/new-user'
import { Route as AppAdminUserGroupsNewUserGroupRouteImport } from './pages/_app/admin/user-groups/new-user-group'
import { Route as AppRegistrationsSalesGroupGroupIdIndexRouteImport } from './pages/_app/registrations/sales-group/$groupId/index'
import { Route as AppRegistrationsProductsProductIdIndexRouteImport } from './pages/_app/registrations/products/$productId/index'
import { Route as AppRegistrationsPriceTablesPriceTableIdIndexRouteImport } from './pages/_app/registrations/price-tables/$priceTableId/index'
import { Route as AppRegistrationsPaymentConditionsConditionIdIndexRouteImport } from './pages/_app/registrations/payment-conditions/$conditionId/index'
import { Route as AppRegistrationsApprovalLevelsLevelIdIndexRouteImport } from './pages/_app/registrations/approval-levels/$levelId/index'
import { Route as AppOrdersViewOrderIdIndexRouteImport } from './pages/_app/orders/view/$orderId/index'
import { Route as AppOrdersEditOrderIdIndexRouteImport } from './pages/_app/orders/edit/$orderId/index'
import { Route as AppMobileNotificationsNewNotificationIndexRouteImport } from './pages/_app/mobile/notifications/new-notification/index'
import { Route as AppMobileNotificationsNotificationIdIndexRouteImport } from './pages/_app/mobile/notifications/$notificationId/index'
import { Route as AppMobileLinksLinkIdIndexRouteImport } from './pages/_app/mobile/links/$linkId/index'
import { Route as AppMobileCommunicationsCommunicationIdIndexRouteImport } from './pages/_app/mobile/communications/$communicationId/index'
import { Route as AppBudgetsViewOrderIdIndexRouteImport } from './pages/_app/budgets/view/$orderId/index'
import { Route as AppBudgetsEditOrderIdIndexRouteImport } from './pages/_app/budgets/edit/$orderId/index'
import { Route as AppAdminUsersUserIdIndexRouteImport } from './pages/_app/admin/users/$userId/index'
import { Route as AppAdminUserGroupsGroupIdIndexRouteImport } from './pages/_app/admin/user-groups/$groupId/index'
import { Route as AppAdminSettingsSettingIdIndexRouteImport } from './pages/_app/admin/settings/$settingId/index'
import { Route as AppRegistrationsCustomersCustomerIdPriceTablesIndexRouteImport } from './pages/_app/registrations/customers/$customerId/price-tables/index'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOutletIndexRoute = AppOutletIndexRouteImport.update({
  id: '/outlet/',
  path: '/outlet/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppBudgetsIndexRoute = AppBudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppApprovalsIndexRoute = AppApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrdersNewOrderRoute = AppOrdersNewOrderRouteImport.update({
  id: '/orders/new-order',
  path: '/orders/new-order',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppBudgetsNewBudgetRoute = AppBudgetsNewBudgetRouteImport.update({
  id: '/budgets/new-budget',
  path: '/budgets/new-budget',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppSystemSyncStatusIndexRoute =
  AppSystemSyncStatusIndexRouteImport.update({
    id: '/system/sync-status/',
    path: '/system/sync-status/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppStockProductStockIndexRoute =
  AppStockProductStockIndexRouteImport.update({
    id: '/stock/product-stock/',
    path: '/stock/product-stock/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppStockEsli011IndexRoute = AppStockEsli011IndexRouteImport.update({
  id: '/stock/esli011/',
  path: '/stock/esli011/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppReportsDashboardProductGroupsIndexRoute =
  AppReportsDashboardProductGroupsIndexRouteImport.update({
    id: '/reports/dashboard-product-groups/',
    path: '/reports/dashboard-product-groups/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppReportsCustomersListIndexRoute =
  AppReportsCustomersListIndexRouteImport.update({
    id: '/reports/customers-list/',
    path: '/reports/customers-list/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppReportsComissaoIndexRoute = AppReportsComissaoIndexRouteImport.update({
  id: '/reports/comissao/',
  path: '/reports/comissao/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppRegistrationsSalesGroupIndexRoute =
  AppRegistrationsSalesGroupIndexRouteImport.update({
    id: '/registrations/sales-group/',
    path: '/registrations/sales-group/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistrationsRepresentativeGoalsIndexRoute =
  AppRegistrationsRepresentativeGoalsIndexRouteImport.update({
    id: '/registrations/representative-goals/',
    path: '/registrations/representative-goals/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistrationsProductsIndexRoute =
  AppRegistrationsProductsIndexRouteImport.update({
    id: '/registrations/products/',
    path: '/registrations/products/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistrationsPriceTablesIndexRoute =
  AppRegistrationsPriceTablesIndexRouteImport.update({
    id: '/registrations/price-tables/',
    path: '/registrations/price-tables/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistrationsPaymentConditionsIndexRoute =
  AppRegistrationsPaymentConditionsIndexRouteImport.update({
    id: '/registrations/payment-conditions/',
    path: '/registrations/payment-conditions/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistrationsCustomersIndexRoute =
  AppRegistrationsCustomersIndexRouteImport.update({
    id: '/registrations/customers/',
    path: '/registrations/customers/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistrationsApprovalLevelsIndexRoute =
  AppRegistrationsApprovalLevelsIndexRouteImport.update({
    id: '/registrations/approval-levels/',
    path: '/registrations/approval-levels/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppOrdersOrderIdIndexRoute = AppOrdersOrderIdIndexRouteImport.update({
  id: '/orders/$orderId/',
  path: '/orders/$orderId/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppMobileNotificationsIndexRoute =
  AppMobileNotificationsIndexRouteImport.update({
    id: '/mobile/notifications/',
    path: '/mobile/notifications/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppMobileLinksIndexRoute = AppMobileLinksIndexRouteImport.update({
  id: '/mobile/links/',
  path: '/mobile/links/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppMobileCommunicationsIndexRoute =
  AppMobileCommunicationsIndexRouteImport.update({
    id: '/mobile/communications/',
    path: '/mobile/communications/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppAdminUserGroupsIndexRoute = AppAdminUserGroupsIndexRouteImport.update({
  id: '/admin/user-groups/',
  path: '/admin/user-groups/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppAdminSettingsIndexRoute = AppAdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppRegistrationsSalesGroupNewGroupRoute =
  AppRegistrationsSalesGroupNewGroupRouteImport.update({
    id: '/registrations/sales-group/new-group',
    path: '/registrations/sales-group/new-group',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistrationsApprovalLevelsNewLevelRoute =
  AppRegistrationsApprovalLevelsNewLevelRouteImport.update({
    id: '/registrations/approval-levels/new-level',
    path: '/registrations/approval-levels/new-level',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppMobileLinksNewLinkRoute = AppMobileLinksNewLinkRouteImport.update({
  id: '/mobile/links/new-link',
  path: '/mobile/links/new-link',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppMobileCommunicationsNewCommunicateRoute =
  AppMobileCommunicationsNewCommunicateRouteImport.update({
    id: '/mobile/communications/new-communicate',
    path: '/mobile/communications/new-communicate',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppAdminUsersNewUserRoute = AppAdminUsersNewUserRouteImport.update({
  id: '/admin/users/new-user',
  path: '/admin/users/new-user',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppAdminUserGroupsNewUserGroupRoute =
  AppAdminUserGroupsNewUserGroupRouteImport.update({
    id: '/admin/user-groups/new-user-group',
    path: '/admin/user-groups/new-user-group',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistrationsSalesGroupGroupIdIndexRoute =
  AppRegistrationsSalesGroupGroupIdIndexRouteImport.update({
    id: '/registrations/sales-group/$groupId/',
    path: '/registrations/sales-group/$groupId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistrationsProductsProductIdIndexRoute =
  AppRegistrationsProductsProductIdIndexRouteImport.update({
    id: '/registrations/products/$productId/',
    path: '/registrations/products/$productId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistrationsPriceTablesPriceTableIdIndexRoute =
  AppRegistrationsPriceTablesPriceTableIdIndexRouteImport.update({
    id: '/registrations/price-tables/$priceTableId/',
    path: '/registrations/price-tables/$priceTableId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistrationsPaymentConditionsConditionIdIndexRoute =
  AppRegistrationsPaymentConditionsConditionIdIndexRouteImport.update({
    id: '/registrations/payment-conditions/$conditionId/',
    path: '/registrations/payment-conditions/$conditionId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistrationsApprovalLevelsLevelIdIndexRoute =
  AppRegistrationsApprovalLevelsLevelIdIndexRouteImport.update({
    id: '/registrations/approval-levels/$levelId/',
    path: '/registrations/approval-levels/$levelId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppOrdersViewOrderIdIndexRoute =
  AppOrdersViewOrderIdIndexRouteImport.update({
    id: '/orders/view/$orderId/',
    path: '/orders/view/$orderId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppOrdersEditOrderIdIndexRoute =
  AppOrdersEditOrderIdIndexRouteImport.update({
    id: '/orders/edit/$orderId/',
    path: '/orders/edit/$orderId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppMobileNotificationsNewNotificationIndexRoute =
  AppMobileNotificationsNewNotificationIndexRouteImport.update({
    id: '/mobile/notifications/new-notification/',
    path: '/mobile/notifications/new-notification/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppMobileNotificationsNotificationIdIndexRoute =
  AppMobileNotificationsNotificationIdIndexRouteImport.update({
    id: '/mobile/notifications/$notificationId/',
    path: '/mobile/notifications/$notificationId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppMobileLinksLinkIdIndexRoute =
  AppMobileLinksLinkIdIndexRouteImport.update({
    id: '/mobile/links/$linkId/',
    path: '/mobile/links/$linkId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppMobileCommunicationsCommunicationIdIndexRoute =
  AppMobileCommunicationsCommunicationIdIndexRouteImport.update({
    id: '/mobile/communications/$communicationId/',
    path: '/mobile/communications/$communicationId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppBudgetsViewOrderIdIndexRoute =
  AppBudgetsViewOrderIdIndexRouteImport.update({
    id: '/budgets/view/$orderId/',
    path: '/budgets/view/$orderId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppBudgetsEditOrderIdIndexRoute =
  AppBudgetsEditOrderIdIndexRouteImport.update({
    id: '/budgets/edit/$orderId/',
    path: '/budgets/edit/$orderId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppAdminUsersUserIdIndexRoute =
  AppAdminUsersUserIdIndexRouteImport.update({
    id: '/admin/users/$userId/',
    path: '/admin/users/$userId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppAdminUserGroupsGroupIdIndexRoute =
  AppAdminUserGroupsGroupIdIndexRouteImport.update({
    id: '/admin/user-groups/$groupId/',
    path: '/admin/user-groups/$groupId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppAdminSettingsSettingIdIndexRoute =
  AppAdminSettingsSettingIdIndexRouteImport.update({
    id: '/admin/settings/$settingId/',
    path: '/admin/settings/$settingId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistrationsCustomersCustomerIdPriceTablesIndexRoute =
  AppRegistrationsCustomersCustomerIdPriceTablesIndexRouteImport.update({
    id: '/registrations/customers/$customerId/price-tables/',
    path: '/registrations/customers/$customerId/price-tables/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/budgets/new-budget': typeof AppBudgetsNewBudgetRoute
  '/orders/new-order': typeof AppOrdersNewOrderRoute
  '/approvals': typeof AppApprovalsIndexRoute
  '/budgets': typeof AppBudgetsIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/outlet': typeof AppOutletIndexRoute
  '/admin/user-groups/new-user-group': typeof AppAdminUserGroupsNewUserGroupRoute
  '/admin/users/new-user': typeof AppAdminUsersNewUserRoute
  '/mobile/communications/new-communicate': typeof AppMobileCommunicationsNewCommunicateRoute
  '/mobile/links/new-link': typeof AppMobileLinksNewLinkRoute
  '/registrations/approval-levels/new-level': typeof AppRegistrationsApprovalLevelsNewLevelRoute
  '/registrations/sales-group/new-group': typeof AppRegistrationsSalesGroupNewGroupRoute
  '/admin/settings': typeof AppAdminSettingsIndexRoute
  '/admin/user-groups': typeof AppAdminUserGroupsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/mobile/communications': typeof AppMobileCommunicationsIndexRoute
  '/mobile/links': typeof AppMobileLinksIndexRoute
  '/mobile/notifications': typeof AppMobileNotificationsIndexRoute
  '/orders/$orderId': typeof AppOrdersOrderIdIndexRoute
  '/registrations/approval-levels': typeof AppRegistrationsApprovalLevelsIndexRoute
  '/registrations/customers': typeof AppRegistrationsCustomersIndexRoute
  '/registrations/payment-conditions': typeof AppRegistrationsPaymentConditionsIndexRoute
  '/registrations/price-tables': typeof AppRegistrationsPriceTablesIndexRoute
  '/registrations/products': typeof AppRegistrationsProductsIndexRoute
  '/registrations/representative-goals': typeof AppRegistrationsRepresentativeGoalsIndexRoute
  '/registrations/sales-group': typeof AppRegistrationsSalesGroupIndexRoute
  '/reports/comissao': typeof AppReportsComissaoIndexRoute
  '/reports/customers-list': typeof AppReportsCustomersListIndexRoute
  '/reports/dashboard-product-groups': typeof AppReportsDashboardProductGroupsIndexRoute
  '/stock/esli011': typeof AppStockEsli011IndexRoute
  '/stock/product-stock': typeof AppStockProductStockIndexRoute
  '/system/sync-status': typeof AppSystemSyncStatusIndexRoute
  '/admin/settings/$settingId': typeof AppAdminSettingsSettingIdIndexRoute
  '/admin/user-groups/$groupId': typeof AppAdminUserGroupsGroupIdIndexRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdIndexRoute
  '/budgets/edit/$orderId': typeof AppBudgetsEditOrderIdIndexRoute
  '/budgets/view/$orderId': typeof AppBudgetsViewOrderIdIndexRoute
  '/mobile/communications/$communicationId': typeof AppMobileCommunicationsCommunicationIdIndexRoute
  '/mobile/links/$linkId': typeof AppMobileLinksLinkIdIndexRoute
  '/mobile/notifications/$notificationId': typeof AppMobileNotificationsNotificationIdIndexRoute
  '/mobile/notifications/new-notification': typeof AppMobileNotificationsNewNotificationIndexRoute
  '/orders/edit/$orderId': typeof AppOrdersEditOrderIdIndexRoute
  '/orders/view/$orderId': typeof AppOrdersViewOrderIdIndexRoute
  '/registrations/approval-levels/$levelId': typeof AppRegistrationsApprovalLevelsLevelIdIndexRoute
  '/registrations/payment-conditions/$conditionId': typeof AppRegistrationsPaymentConditionsConditionIdIndexRoute
  '/registrations/price-tables/$priceTableId': typeof AppRegistrationsPriceTablesPriceTableIdIndexRoute
  '/registrations/products/$productId': typeof AppRegistrationsProductsProductIdIndexRoute
  '/registrations/sales-group/$groupId': typeof AppRegistrationsSalesGroupGroupIdIndexRoute
  '/registrations/customers/$customerId/price-tables': typeof AppRegistrationsCustomersCustomerIdPriceTablesIndexRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/budgets/new-budget': typeof AppBudgetsNewBudgetRoute
  '/orders/new-order': typeof AppOrdersNewOrderRoute
  '/approvals': typeof AppApprovalsIndexRoute
  '/budgets': typeof AppBudgetsIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/outlet': typeof AppOutletIndexRoute
  '/admin/user-groups/new-user-group': typeof AppAdminUserGroupsNewUserGroupRoute
  '/admin/users/new-user': typeof AppAdminUsersNewUserRoute
  '/mobile/communications/new-communicate': typeof AppMobileCommunicationsNewCommunicateRoute
  '/mobile/links/new-link': typeof AppMobileLinksNewLinkRoute
  '/registrations/approval-levels/new-level': typeof AppRegistrationsApprovalLevelsNewLevelRoute
  '/registrations/sales-group/new-group': typeof AppRegistrationsSalesGroupNewGroupRoute
  '/admin/settings': typeof AppAdminSettingsIndexRoute
  '/admin/user-groups': typeof AppAdminUserGroupsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/mobile/communications': typeof AppMobileCommunicationsIndexRoute
  '/mobile/links': typeof AppMobileLinksIndexRoute
  '/mobile/notifications': typeof AppMobileNotificationsIndexRoute
  '/orders/$orderId': typeof AppOrdersOrderIdIndexRoute
  '/registrations/approval-levels': typeof AppRegistrationsApprovalLevelsIndexRoute
  '/registrations/customers': typeof AppRegistrationsCustomersIndexRoute
  '/registrations/payment-conditions': typeof AppRegistrationsPaymentConditionsIndexRoute
  '/registrations/price-tables': typeof AppRegistrationsPriceTablesIndexRoute
  '/registrations/products': typeof AppRegistrationsProductsIndexRoute
  '/registrations/representative-goals': typeof AppRegistrationsRepresentativeGoalsIndexRoute
  '/registrations/sales-group': typeof AppRegistrationsSalesGroupIndexRoute
  '/reports/comissao': typeof AppReportsComissaoIndexRoute
  '/reports/customers-list': typeof AppReportsCustomersListIndexRoute
  '/reports/dashboard-product-groups': typeof AppReportsDashboardProductGroupsIndexRoute
  '/stock/esli011': typeof AppStockEsli011IndexRoute
  '/stock/product-stock': typeof AppStockProductStockIndexRoute
  '/system/sync-status': typeof AppSystemSyncStatusIndexRoute
  '/admin/settings/$settingId': typeof AppAdminSettingsSettingIdIndexRoute
  '/admin/user-groups/$groupId': typeof AppAdminUserGroupsGroupIdIndexRoute
  '/admin/users/$userId': typeof AppAdminUsersUserIdIndexRoute
  '/budgets/edit/$orderId': typeof AppBudgetsEditOrderIdIndexRoute
  '/budgets/view/$orderId': typeof AppBudgetsViewOrderIdIndexRoute
  '/mobile/communications/$communicationId': typeof AppMobileCommunicationsCommunicationIdIndexRoute
  '/mobile/links/$linkId': typeof AppMobileLinksLinkIdIndexRoute
  '/mobile/notifications/$notificationId': typeof AppMobileNotificationsNotificationIdIndexRoute
  '/mobile/notifications/new-notification': typeof AppMobileNotificationsNewNotificationIndexRoute
  '/orders/edit/$orderId': typeof AppOrdersEditOrderIdIndexRoute
  '/orders/view/$orderId': typeof AppOrdersViewOrderIdIndexRoute
  '/registrations/approval-levels/$levelId': typeof AppRegistrationsApprovalLevelsLevelIdIndexRoute
  '/registrations/payment-conditions/$conditionId': typeof AppRegistrationsPaymentConditionsConditionIdIndexRoute
  '/registrations/price-tables/$priceTableId': typeof AppRegistrationsPriceTablesPriceTableIdIndexRoute
  '/registrations/products/$productId': typeof AppRegistrationsProductsProductIdIndexRoute
  '/registrations/sales-group/$groupId': typeof AppRegistrationsSalesGroupGroupIdIndexRoute
  '/registrations/customers/$customerId/price-tables': typeof AppRegistrationsCustomersCustomerIdPriceTablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/budgets/new-budget': typeof AppBudgetsNewBudgetRoute
  '/_app/orders/new-order': typeof AppOrdersNewOrderRoute
  '/_app/approvals/': typeof AppApprovalsIndexRoute
  '/_app/budgets/': typeof AppBudgetsIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/outlet/': typeof AppOutletIndexRoute
  '/_app/admin/user-groups/new-user-group': typeof AppAdminUserGroupsNewUserGroupRoute
  '/_app/admin/users/new-user': typeof AppAdminUsersNewUserRoute
  '/_app/mobile/communications/new-communicate': typeof AppMobileCommunicationsNewCommunicateRoute
  '/_app/mobile/links/new-link': typeof AppMobileLinksNewLinkRoute
  '/_app/registrations/approval-levels/new-level': typeof AppRegistrationsApprovalLevelsNewLevelRoute
  '/_app/registrations/sales-group/new-group': typeof AppRegistrationsSalesGroupNewGroupRoute
  '/_app/admin/settings/': typeof AppAdminSettingsIndexRoute
  '/_app/admin/user-groups/': typeof AppAdminUserGroupsIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/mobile/communications/': typeof AppMobileCommunicationsIndexRoute
  '/_app/mobile/links/': typeof AppMobileLinksIndexRoute
  '/_app/mobile/notifications/': typeof AppMobileNotificationsIndexRoute
  '/_app/orders/$orderId/': typeof AppOrdersOrderIdIndexRoute
  '/_app/registrations/approval-levels/': typeof AppRegistrationsApprovalLevelsIndexRoute
  '/_app/registrations/customers/': typeof AppRegistrationsCustomersIndexRoute
  '/_app/registrations/payment-conditions/': typeof AppRegistrationsPaymentConditionsIndexRoute
  '/_app/registrations/price-tables/': typeof AppRegistrationsPriceTablesIndexRoute
  '/_app/registrations/products/': typeof AppRegistrationsProductsIndexRoute
  '/_app/registrations/representative-goals/': typeof AppRegistrationsRepresentativeGoalsIndexRoute
  '/_app/registrations/sales-group/': typeof AppRegistrationsSalesGroupIndexRoute
  '/_app/reports/comissao/': typeof AppReportsComissaoIndexRoute
  '/_app/reports/customers-list/': typeof AppReportsCustomersListIndexRoute
  '/_app/reports/dashboard-product-groups/': typeof AppReportsDashboardProductGroupsIndexRoute
  '/_app/stock/esli011/': typeof AppStockEsli011IndexRoute
  '/_app/stock/product-stock/': typeof AppStockProductStockIndexRoute
  '/_app/system/sync-status/': typeof AppSystemSyncStatusIndexRoute
  '/_app/admin/settings/$settingId/': typeof AppAdminSettingsSettingIdIndexRoute
  '/_app/admin/user-groups/$groupId/': typeof AppAdminUserGroupsGroupIdIndexRoute
  '/_app/admin/users/$userId/': typeof AppAdminUsersUserIdIndexRoute
  '/_app/budgets/edit/$orderId/': typeof AppBudgetsEditOrderIdIndexRoute
  '/_app/budgets/view/$orderId/': typeof AppBudgetsViewOrderIdIndexRoute
  '/_app/mobile/communications/$communicationId/': typeof AppMobileCommunicationsCommunicationIdIndexRoute
  '/_app/mobile/links/$linkId/': typeof AppMobileLinksLinkIdIndexRoute
  '/_app/mobile/notifications/$notificationId/': typeof AppMobileNotificationsNotificationIdIndexRoute
  '/_app/mobile/notifications/new-notification/': typeof AppMobileNotificationsNewNotificationIndexRoute
  '/_app/orders/edit/$orderId/': typeof AppOrdersEditOrderIdIndexRoute
  '/_app/orders/view/$orderId/': typeof AppOrdersViewOrderIdIndexRoute
  '/_app/registrations/approval-levels/$levelId/': typeof AppRegistrationsApprovalLevelsLevelIdIndexRoute
  '/_app/registrations/payment-conditions/$conditionId/': typeof AppRegistrationsPaymentConditionsConditionIdIndexRoute
  '/_app/registrations/price-tables/$priceTableId/': typeof AppRegistrationsPriceTablesPriceTableIdIndexRoute
  '/_app/registrations/products/$productId/': typeof AppRegistrationsProductsProductIdIndexRoute
  '/_app/registrations/sales-group/$groupId/': typeof AppRegistrationsSalesGroupGroupIdIndexRoute
  '/_app/registrations/customers/$customerId/price-tables/': typeof AppRegistrationsCustomersCustomerIdPriceTablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/login'
    | '/'
    | '/budgets/new-budget'
    | '/orders/new-order'
    | '/approvals'
    | '/budgets'
    | '/dashboard'
    | '/orders'
    | '/outlet'
    | '/admin/user-groups/new-user-group'
    | '/admin/users/new-user'
    | '/mobile/communications/new-communicate'
    | '/mobile/links/new-link'
    | '/registrations/approval-levels/new-level'
    | '/registrations/sales-group/new-group'
    | '/admin/settings'
    | '/admin/user-groups'
    | '/admin/users'
    | '/mobile/communications'
    | '/mobile/links'
    | '/mobile/notifications'
    | '/orders/$orderId'
    | '/registrations/approval-levels'
    | '/registrations/customers'
    | '/registrations/payment-conditions'
    | '/registrations/price-tables'
    | '/registrations/products'
    | '/registrations/representative-goals'
    | '/registrations/sales-group'
    | '/reports/comissao'
    | '/reports/customers-list'
    | '/reports/dashboard-product-groups'
    | '/stock/esli011'
    | '/stock/product-stock'
    | '/system/sync-status'
    | '/admin/settings/$settingId'
    | '/admin/user-groups/$groupId'
    | '/admin/users/$userId'
    | '/budgets/edit/$orderId'
    | '/budgets/view/$orderId'
    | '/mobile/communications/$communicationId'
    | '/mobile/links/$linkId'
    | '/mobile/notifications/$notificationId'
    | '/mobile/notifications/new-notification'
    | '/orders/edit/$orderId'
    | '/orders/view/$orderId'
    | '/registrations/approval-levels/$levelId'
    | '/registrations/payment-conditions/$conditionId'
    | '/registrations/price-tables/$priceTableId'
    | '/registrations/products/$productId'
    | '/registrations/sales-group/$groupId'
    | '/registrations/customers/$customerId/price-tables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/login'
    | '/'
    | '/budgets/new-budget'
    | '/orders/new-order'
    | '/approvals'
    | '/budgets'
    | '/dashboard'
    | '/orders'
    | '/outlet'
    | '/admin/user-groups/new-user-group'
    | '/admin/users/new-user'
    | '/mobile/communications/new-communicate'
    | '/mobile/links/new-link'
    | '/registrations/approval-levels/new-level'
    | '/registrations/sales-group/new-group'
    | '/admin/settings'
    | '/admin/user-groups'
    | '/admin/users'
    | '/mobile/communications'
    | '/mobile/links'
    | '/mobile/notifications'
    | '/orders/$orderId'
    | '/registrations/approval-levels'
    | '/registrations/customers'
    | '/registrations/payment-conditions'
    | '/registrations/price-tables'
    | '/registrations/products'
    | '/registrations/representative-goals'
    | '/registrations/sales-group'
    | '/reports/comissao'
    | '/reports/customers-list'
    | '/reports/dashboard-product-groups'
    | '/stock/esli011'
    | '/stock/product-stock'
    | '/system/sync-status'
    | '/admin/settings/$settingId'
    | '/admin/user-groups/$groupId'
    | '/admin/users/$userId'
    | '/budgets/edit/$orderId'
    | '/budgets/view/$orderId'
    | '/mobile/communications/$communicationId'
    | '/mobile/links/$linkId'
    | '/mobile/notifications/$notificationId'
    | '/mobile/notifications/new-notification'
    | '/orders/edit/$orderId'
    | '/orders/view/$orderId'
    | '/registrations/approval-levels/$levelId'
    | '/registrations/payment-conditions/$conditionId'
    | '/registrations/price-tables/$priceTableId'
    | '/registrations/products/$productId'
    | '/registrations/sales-group/$groupId'
    | '/registrations/customers/$customerId/price-tables'
  id:
    | '__root__'
    | '/_app'
    | '/auth/login'
    | '/_app/'
    | '/_app/budgets/new-budget'
    | '/_app/orders/new-order'
    | '/_app/approvals/'
    | '/_app/budgets/'
    | '/_app/dashboard/'
    | '/_app/orders/'
    | '/_app/outlet/'
    | '/_app/admin/user-groups/new-user-group'
    | '/_app/admin/users/new-user'
    | '/_app/mobile/communications/new-communicate'
    | '/_app/mobile/links/new-link'
    | '/_app/registrations/approval-levels/new-level'
    | '/_app/registrations/sales-group/new-group'
    | '/_app/admin/settings/'
    | '/_app/admin/user-groups/'
    | '/_app/admin/users/'
    | '/_app/mobile/communications/'
    | '/_app/mobile/links/'
    | '/_app/mobile/notifications/'
    | '/_app/orders/$orderId/'
    | '/_app/registrations/approval-levels/'
    | '/_app/registrations/customers/'
    | '/_app/registrations/payment-conditions/'
    | '/_app/registrations/price-tables/'
    | '/_app/registrations/products/'
    | '/_app/registrations/representative-goals/'
    | '/_app/registrations/sales-group/'
    | '/_app/reports/comissao/'
    | '/_app/reports/customers-list/'
    | '/_app/reports/dashboard-product-groups/'
    | '/_app/stock/esli011/'
    | '/_app/stock/product-stock/'
    | '/_app/system/sync-status/'
    | '/_app/admin/settings/$settingId/'
    | '/_app/admin/user-groups/$groupId/'
    | '/_app/admin/users/$userId/'
    | '/_app/budgets/edit/$orderId/'
    | '/_app/budgets/view/$orderId/'
    | '/_app/mobile/communications/$communicationId/'
    | '/_app/mobile/links/$linkId/'
    | '/_app/mobile/notifications/$notificationId/'
    | '/_app/mobile/notifications/new-notification/'
    | '/_app/orders/edit/$orderId/'
    | '/_app/orders/view/$orderId/'
    | '/_app/registrations/approval-levels/$levelId/'
    | '/_app/registrations/payment-conditions/$conditionId/'
    | '/_app/registrations/price-tables/$priceTableId/'
    | '/_app/registrations/products/$productId/'
    | '/_app/registrations/sales-group/$groupId/'
    | '/_app/registrations/customers/$customerId/price-tables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/outlet/': {
      id: '/_app/outlet/'
      path: '/outlet'
      fullPath: '/outlet'
      preLoaderRoute: typeof AppOutletIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/budgets/': {
      id: '/_app/budgets/'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AppBudgetsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/approvals/': {
      id: '/_app/approvals/'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/orders/new-order': {
      id: '/_app/orders/new-order'
      path: '/orders/new-order'
      fullPath: '/orders/new-order'
      preLoaderRoute: typeof AppOrdersNewOrderRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/budgets/new-budget': {
      id: '/_app/budgets/new-budget'
      path: '/budgets/new-budget'
      fullPath: '/budgets/new-budget'
      preLoaderRoute: typeof AppBudgetsNewBudgetRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/system/sync-status/': {
      id: '/_app/system/sync-status/'
      path: '/system/sync-status'
      fullPath: '/system/sync-status'
      preLoaderRoute: typeof AppSystemSyncStatusIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/stock/product-stock/': {
      id: '/_app/stock/product-stock/'
      path: '/stock/product-stock'
      fullPath: '/stock/product-stock'
      preLoaderRoute: typeof AppStockProductStockIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/stock/esli011/': {
      id: '/_app/stock/esli011/'
      path: '/stock/esli011'
      fullPath: '/stock/esli011'
      preLoaderRoute: typeof AppStockEsli011IndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/reports/dashboard-product-groups/': {
      id: '/_app/reports/dashboard-product-groups/'
      path: '/reports/dashboard-product-groups'
      fullPath: '/reports/dashboard-product-groups'
      preLoaderRoute: typeof AppReportsDashboardProductGroupsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/reports/customers-list/': {
      id: '/_app/reports/customers-list/'
      path: '/reports/customers-list'
      fullPath: '/reports/customers-list'
      preLoaderRoute: typeof AppReportsCustomersListIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/reports/comissao/': {
      id: '/_app/reports/comissao/'
      path: '/reports/comissao'
      fullPath: '/reports/comissao'
      preLoaderRoute: typeof AppReportsComissaoIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/sales-group/': {
      id: '/_app/registrations/sales-group/'
      path: '/registrations/sales-group'
      fullPath: '/registrations/sales-group'
      preLoaderRoute: typeof AppRegistrationsSalesGroupIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/representative-goals/': {
      id: '/_app/registrations/representative-goals/'
      path: '/registrations/representative-goals'
      fullPath: '/registrations/representative-goals'
      preLoaderRoute: typeof AppRegistrationsRepresentativeGoalsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/products/': {
      id: '/_app/registrations/products/'
      path: '/registrations/products'
      fullPath: '/registrations/products'
      preLoaderRoute: typeof AppRegistrationsProductsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/price-tables/': {
      id: '/_app/registrations/price-tables/'
      path: '/registrations/price-tables'
      fullPath: '/registrations/price-tables'
      preLoaderRoute: typeof AppRegistrationsPriceTablesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/payment-conditions/': {
      id: '/_app/registrations/payment-conditions/'
      path: '/registrations/payment-conditions'
      fullPath: '/registrations/payment-conditions'
      preLoaderRoute: typeof AppRegistrationsPaymentConditionsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/customers/': {
      id: '/_app/registrations/customers/'
      path: '/registrations/customers'
      fullPath: '/registrations/customers'
      preLoaderRoute: typeof AppRegistrationsCustomersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/approval-levels/': {
      id: '/_app/registrations/approval-levels/'
      path: '/registrations/approval-levels'
      fullPath: '/registrations/approval-levels'
      preLoaderRoute: typeof AppRegistrationsApprovalLevelsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/orders/$orderId/': {
      id: '/_app/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/mobile/notifications/': {
      id: '/_app/mobile/notifications/'
      path: '/mobile/notifications'
      fullPath: '/mobile/notifications'
      preLoaderRoute: typeof AppMobileNotificationsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/mobile/links/': {
      id: '/_app/mobile/links/'
      path: '/mobile/links'
      fullPath: '/mobile/links'
      preLoaderRoute: typeof AppMobileLinksIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/mobile/communications/': {
      id: '/_app/mobile/communications/'
      path: '/mobile/communications'
      fullPath: '/mobile/communications'
      preLoaderRoute: typeof AppMobileCommunicationsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/admin/user-groups/': {
      id: '/_app/admin/user-groups/'
      path: '/admin/user-groups'
      fullPath: '/admin/user-groups'
      preLoaderRoute: typeof AppAdminUserGroupsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/admin/settings/': {
      id: '/_app/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/sales-group/new-group': {
      id: '/_app/registrations/sales-group/new-group'
      path: '/registrations/sales-group/new-group'
      fullPath: '/registrations/sales-group/new-group'
      preLoaderRoute: typeof AppRegistrationsSalesGroupNewGroupRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/approval-levels/new-level': {
      id: '/_app/registrations/approval-levels/new-level'
      path: '/registrations/approval-levels/new-level'
      fullPath: '/registrations/approval-levels/new-level'
      preLoaderRoute: typeof AppRegistrationsApprovalLevelsNewLevelRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/mobile/links/new-link': {
      id: '/_app/mobile/links/new-link'
      path: '/mobile/links/new-link'
      fullPath: '/mobile/links/new-link'
      preLoaderRoute: typeof AppMobileLinksNewLinkRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/mobile/communications/new-communicate': {
      id: '/_app/mobile/communications/new-communicate'
      path: '/mobile/communications/new-communicate'
      fullPath: '/mobile/communications/new-communicate'
      preLoaderRoute: typeof AppMobileCommunicationsNewCommunicateRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/admin/users/new-user': {
      id: '/_app/admin/users/new-user'
      path: '/admin/users/new-user'
      fullPath: '/admin/users/new-user'
      preLoaderRoute: typeof AppAdminUsersNewUserRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/admin/user-groups/new-user-group': {
      id: '/_app/admin/user-groups/new-user-group'
      path: '/admin/user-groups/new-user-group'
      fullPath: '/admin/user-groups/new-user-group'
      preLoaderRoute: typeof AppAdminUserGroupsNewUserGroupRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/sales-group/$groupId/': {
      id: '/_app/registrations/sales-group/$groupId/'
      path: '/registrations/sales-group/$groupId'
      fullPath: '/registrations/sales-group/$groupId'
      preLoaderRoute: typeof AppRegistrationsSalesGroupGroupIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/products/$productId/': {
      id: '/_app/registrations/products/$productId/'
      path: '/registrations/products/$productId'
      fullPath: '/registrations/products/$productId'
      preLoaderRoute: typeof AppRegistrationsProductsProductIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/price-tables/$priceTableId/': {
      id: '/_app/registrations/price-tables/$priceTableId/'
      path: '/registrations/price-tables/$priceTableId'
      fullPath: '/registrations/price-tables/$priceTableId'
      preLoaderRoute: typeof AppRegistrationsPriceTablesPriceTableIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/payment-conditions/$conditionId/': {
      id: '/_app/registrations/payment-conditions/$conditionId/'
      path: '/registrations/payment-conditions/$conditionId'
      fullPath: '/registrations/payment-conditions/$conditionId'
      preLoaderRoute: typeof AppRegistrationsPaymentConditionsConditionIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/approval-levels/$levelId/': {
      id: '/_app/registrations/approval-levels/$levelId/'
      path: '/registrations/approval-levels/$levelId'
      fullPath: '/registrations/approval-levels/$levelId'
      preLoaderRoute: typeof AppRegistrationsApprovalLevelsLevelIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/orders/view/$orderId/': {
      id: '/_app/orders/view/$orderId/'
      path: '/orders/view/$orderId'
      fullPath: '/orders/view/$orderId'
      preLoaderRoute: typeof AppOrdersViewOrderIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/orders/edit/$orderId/': {
      id: '/_app/orders/edit/$orderId/'
      path: '/orders/edit/$orderId'
      fullPath: '/orders/edit/$orderId'
      preLoaderRoute: typeof AppOrdersEditOrderIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/mobile/notifications/new-notification/': {
      id: '/_app/mobile/notifications/new-notification/'
      path: '/mobile/notifications/new-notification'
      fullPath: '/mobile/notifications/new-notification'
      preLoaderRoute: typeof AppMobileNotificationsNewNotificationIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/mobile/notifications/$notificationId/': {
      id: '/_app/mobile/notifications/$notificationId/'
      path: '/mobile/notifications/$notificationId'
      fullPath: '/mobile/notifications/$notificationId'
      preLoaderRoute: typeof AppMobileNotificationsNotificationIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/mobile/links/$linkId/': {
      id: '/_app/mobile/links/$linkId/'
      path: '/mobile/links/$linkId'
      fullPath: '/mobile/links/$linkId'
      preLoaderRoute: typeof AppMobileLinksLinkIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/mobile/communications/$communicationId/': {
      id: '/_app/mobile/communications/$communicationId/'
      path: '/mobile/communications/$communicationId'
      fullPath: '/mobile/communications/$communicationId'
      preLoaderRoute: typeof AppMobileCommunicationsCommunicationIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/budgets/view/$orderId/': {
      id: '/_app/budgets/view/$orderId/'
      path: '/budgets/view/$orderId'
      fullPath: '/budgets/view/$orderId'
      preLoaderRoute: typeof AppBudgetsViewOrderIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/budgets/edit/$orderId/': {
      id: '/_app/budgets/edit/$orderId/'
      path: '/budgets/edit/$orderId'
      fullPath: '/budgets/edit/$orderId'
      preLoaderRoute: typeof AppBudgetsEditOrderIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/admin/users/$userId/': {
      id: '/_app/admin/users/$userId/'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AppAdminUsersUserIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/admin/user-groups/$groupId/': {
      id: '/_app/admin/user-groups/$groupId/'
      path: '/admin/user-groups/$groupId'
      fullPath: '/admin/user-groups/$groupId'
      preLoaderRoute: typeof AppAdminUserGroupsGroupIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/admin/settings/$settingId/': {
      id: '/_app/admin/settings/$settingId/'
      path: '/admin/settings/$settingId'
      fullPath: '/admin/settings/$settingId'
      preLoaderRoute: typeof AppAdminSettingsSettingIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/customers/$customerId/price-tables/': {
      id: '/_app/registrations/customers/$customerId/price-tables/'
      path: '/registrations/customers/$customerId/price-tables'
      fullPath: '/registrations/customers/$customerId/price-tables'
      preLoaderRoute: typeof AppRegistrationsCustomersCustomerIdPriceTablesIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppBudgetsNewBudgetRoute: typeof AppBudgetsNewBudgetRoute
  AppOrdersNewOrderRoute: typeof AppOrdersNewOrderRoute
  AppApprovalsIndexRoute: typeof AppApprovalsIndexRoute
  AppBudgetsIndexRoute: typeof AppBudgetsIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppOutletIndexRoute: typeof AppOutletIndexRoute
  AppAdminUserGroupsNewUserGroupRoute: typeof AppAdminUserGroupsNewUserGroupRoute
  AppAdminUsersNewUserRoute: typeof AppAdminUsersNewUserRoute
  AppMobileCommunicationsNewCommunicateRoute: typeof AppMobileCommunicationsNewCommunicateRoute
  AppMobileLinksNewLinkRoute: typeof AppMobileLinksNewLinkRoute
  AppRegistrationsApprovalLevelsNewLevelRoute: typeof AppRegistrationsApprovalLevelsNewLevelRoute
  AppRegistrationsSalesGroupNewGroupRoute: typeof AppRegistrationsSalesGroupNewGroupRoute
  AppAdminSettingsIndexRoute: typeof AppAdminSettingsIndexRoute
  AppAdminUserGroupsIndexRoute: typeof AppAdminUserGroupsIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
  AppMobileCommunicationsIndexRoute: typeof AppMobileCommunicationsIndexRoute
  AppMobileLinksIndexRoute: typeof AppMobileLinksIndexRoute
  AppMobileNotificationsIndexRoute: typeof AppMobileNotificationsIndexRoute
  AppOrdersOrderIdIndexRoute: typeof AppOrdersOrderIdIndexRoute
  AppRegistrationsApprovalLevelsIndexRoute: typeof AppRegistrationsApprovalLevelsIndexRoute
  AppRegistrationsCustomersIndexRoute: typeof AppRegistrationsCustomersIndexRoute
  AppRegistrationsPaymentConditionsIndexRoute: typeof AppRegistrationsPaymentConditionsIndexRoute
  AppRegistrationsPriceTablesIndexRoute: typeof AppRegistrationsPriceTablesIndexRoute
  AppRegistrationsProductsIndexRoute: typeof AppRegistrationsProductsIndexRoute
  AppRegistrationsRepresentativeGoalsIndexRoute: typeof AppRegistrationsRepresentativeGoalsIndexRoute
  AppRegistrationsSalesGroupIndexRoute: typeof AppRegistrationsSalesGroupIndexRoute
  AppReportsComissaoIndexRoute: typeof AppReportsComissaoIndexRoute
  AppReportsCustomersListIndexRoute: typeof AppReportsCustomersListIndexRoute
  AppReportsDashboardProductGroupsIndexRoute: typeof AppReportsDashboardProductGroupsIndexRoute
  AppStockEsli011IndexRoute: typeof AppStockEsli011IndexRoute
  AppStockProductStockIndexRoute: typeof AppStockProductStockIndexRoute
  AppSystemSyncStatusIndexRoute: typeof AppSystemSyncStatusIndexRoute
  AppAdminSettingsSettingIdIndexRoute: typeof AppAdminSettingsSettingIdIndexRoute
  AppAdminUserGroupsGroupIdIndexRoute: typeof AppAdminUserGroupsGroupIdIndexRoute
  AppAdminUsersUserIdIndexRoute: typeof AppAdminUsersUserIdIndexRoute
  AppBudgetsEditOrderIdIndexRoute: typeof AppBudgetsEditOrderIdIndexRoute
  AppBudgetsViewOrderIdIndexRoute: typeof AppBudgetsViewOrderIdIndexRoute
  AppMobileCommunicationsCommunicationIdIndexRoute: typeof AppMobileCommunicationsCommunicationIdIndexRoute
  AppMobileLinksLinkIdIndexRoute: typeof AppMobileLinksLinkIdIndexRoute
  AppMobileNotificationsNotificationIdIndexRoute: typeof AppMobileNotificationsNotificationIdIndexRoute
  AppMobileNotificationsNewNotificationIndexRoute: typeof AppMobileNotificationsNewNotificationIndexRoute
  AppOrdersEditOrderIdIndexRoute: typeof AppOrdersEditOrderIdIndexRoute
  AppOrdersViewOrderIdIndexRoute: typeof AppOrdersViewOrderIdIndexRoute
  AppRegistrationsApprovalLevelsLevelIdIndexRoute: typeof AppRegistrationsApprovalLevelsLevelIdIndexRoute
  AppRegistrationsPaymentConditionsConditionIdIndexRoute: typeof AppRegistrationsPaymentConditionsConditionIdIndexRoute
  AppRegistrationsPriceTablesPriceTableIdIndexRoute: typeof AppRegistrationsPriceTablesPriceTableIdIndexRoute
  AppRegistrationsProductsProductIdIndexRoute: typeof AppRegistrationsProductsProductIdIndexRoute
  AppRegistrationsSalesGroupGroupIdIndexRoute: typeof AppRegistrationsSalesGroupGroupIdIndexRoute
  AppRegistrationsCustomersCustomerIdPriceTablesIndexRoute: typeof AppRegistrationsCustomersCustomerIdPriceTablesIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppBudgetsNewBudgetRoute: AppBudgetsNewBudgetRoute,
  AppOrdersNewOrderRoute: AppOrdersNewOrderRoute,
  AppApprovalsIndexRoute: AppApprovalsIndexRoute,
  AppBudgetsIndexRoute: AppBudgetsIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppOutletIndexRoute: AppOutletIndexRoute,
  AppAdminUserGroupsNewUserGroupRoute: AppAdminUserGroupsNewUserGroupRoute,
  AppAdminUsersNewUserRoute: AppAdminUsersNewUserRoute,
  AppMobileCommunicationsNewCommunicateRoute:
    AppMobileCommunicationsNewCommunicateRoute,
  AppMobileLinksNewLinkRoute: AppMobileLinksNewLinkRoute,
  AppRegistrationsApprovalLevelsNewLevelRoute:
    AppRegistrationsApprovalLevelsNewLevelRoute,
  AppRegistrationsSalesGroupNewGroupRoute:
    AppRegistrationsSalesGroupNewGroupRoute,
  AppAdminSettingsIndexRoute: AppAdminSettingsIndexRoute,
  AppAdminUserGroupsIndexRoute: AppAdminUserGroupsIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
  AppMobileCommunicationsIndexRoute: AppMobileCommunicationsIndexRoute,
  AppMobileLinksIndexRoute: AppMobileLinksIndexRoute,
  AppMobileNotificationsIndexRoute: AppMobileNotificationsIndexRoute,
  AppOrdersOrderIdIndexRoute: AppOrdersOrderIdIndexRoute,
  AppRegistrationsApprovalLevelsIndexRoute:
    AppRegistrationsApprovalLevelsIndexRoute,
  AppRegistrationsCustomersIndexRoute: AppRegistrationsCustomersIndexRoute,
  AppRegistrationsPaymentConditionsIndexRoute:
    AppRegistrationsPaymentConditionsIndexRoute,
  AppRegistrationsPriceTablesIndexRoute: AppRegistrationsPriceTablesIndexRoute,
  AppRegistrationsProductsIndexRoute: AppRegistrationsProductsIndexRoute,
  AppRegistrationsRepresentativeGoalsIndexRoute:
    AppRegistrationsRepresentativeGoalsIndexRoute,
  AppRegistrationsSalesGroupIndexRoute: AppRegistrationsSalesGroupIndexRoute,
  AppReportsComissaoIndexRoute: AppReportsComissaoIndexRoute,
  AppReportsCustomersListIndexRoute: AppReportsCustomersListIndexRoute,
  AppReportsDashboardProductGroupsIndexRoute:
    AppReportsDashboardProductGroupsIndexRoute,
  AppStockEsli011IndexRoute: AppStockEsli011IndexRoute,
  AppStockProductStockIndexRoute: AppStockProductStockIndexRoute,
  AppSystemSyncStatusIndexRoute: AppSystemSyncStatusIndexRoute,
  AppAdminSettingsSettingIdIndexRoute: AppAdminSettingsSettingIdIndexRoute,
  AppAdminUserGroupsGroupIdIndexRoute: AppAdminUserGroupsGroupIdIndexRoute,
  AppAdminUsersUserIdIndexRoute: AppAdminUsersUserIdIndexRoute,
  AppBudgetsEditOrderIdIndexRoute: AppBudgetsEditOrderIdIndexRoute,
  AppBudgetsViewOrderIdIndexRoute: AppBudgetsViewOrderIdIndexRoute,
  AppMobileCommunicationsCommunicationIdIndexRoute:
    AppMobileCommunicationsCommunicationIdIndexRoute,
  AppMobileLinksLinkIdIndexRoute: AppMobileLinksLinkIdIndexRoute,
  AppMobileNotificationsNotificationIdIndexRoute:
    AppMobileNotificationsNotificationIdIndexRoute,
  AppMobileNotificationsNewNotificationIndexRoute:
    AppMobileNotificationsNewNotificationIndexRoute,
  AppOrdersEditOrderIdIndexRoute: AppOrdersEditOrderIdIndexRoute,
  AppOrdersViewOrderIdIndexRoute: AppOrdersViewOrderIdIndexRoute,
  AppRegistrationsApprovalLevelsLevelIdIndexRoute:
    AppRegistrationsApprovalLevelsLevelIdIndexRoute,
  AppRegistrationsPaymentConditionsConditionIdIndexRoute:
    AppRegistrationsPaymentConditionsConditionIdIndexRoute,
  AppRegistrationsPriceTablesPriceTableIdIndexRoute:
    AppRegistrationsPriceTablesPriceTableIdIndexRoute,
  AppRegistrationsProductsProductIdIndexRoute:
    AppRegistrationsProductsProductIdIndexRoute,
  AppRegistrationsSalesGroupGroupIdIndexRoute:
    AppRegistrationsSalesGroupGroupIdIndexRoute,
  AppRegistrationsCustomersCustomerIdPriceTablesIndexRoute:
    AppRegistrationsCustomersCustomerIdPriceTablesIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
