/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppLayoutRouteImport } from './pages/_app/layout'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AuthLoginRouteImport } from './pages/auth/login'
import { Route as AppOutletIndexRouteImport } from './pages/_app/outlet/index'
import { Route as AppOrdersIndexRouteImport } from './pages/_app/orders/index'
import { Route as AppDashboardIndexRouteImport } from './pages/_app/dashboard/index'
import { Route as AppOrdersNewOrderRouteImport } from './pages/_app/orders/new-order'
import { Route as AppBudgetsNewBudgetRouteImport } from './pages/_app/budgets/new-budget'
import { Route as AppSystemSyncStatusIndexRouteImport } from './pages/_app/system/sync-status/index'
import { Route as AppStockProductStockIndexRouteImport } from './pages/_app/stock/product-stock/index'
import { Route as AppStockEsli011IndexRouteImport } from './pages/_app/stock/esli011/index'
import { Route as AppRegistrationsSalesGroupIndexRouteImport } from './pages/_app/registrations/sales-group/index'
import { Route as AppOrdersOrderIdIndexRouteImport } from './pages/_app/orders/$orderId/index'
import { Route as AppAdminUsersIndexRouteImport } from './pages/_app/admin/users/index'
import { Route as AppAdminUserGroupsIndexRouteImport } from './pages/_app/admin/user-groups/index'
import { Route as AppAdminSettingsIndexRouteImport } from './pages/_app/admin/settings/index'
import { Route as AppRegistrationsSalesGroupNewGroupRouteImport } from './pages/_app/registrations/sales-group/new-group'
import { Route as AppAdminUsersNewUserRouteImport } from './pages/_app/admin/users/new-user'
import { Route as AppAdminUserGroupsNewGroupRouteImport } from './pages/_app/admin/user-groups/new-group'
import { Route as AppRegistrationsSalesGroupGroupIdIndexRouteImport } from './pages/_app/registrations/sales-group/$groupId/index'
import { Route as AppAdminUserGroupsGroupIdIndexRouteImport } from './pages/_app/admin/user-groups/$groupId/index'

const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOutletIndexRoute = AppOutletIndexRouteImport.update({
  id: '/outlet/',
  path: '/outlet/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppOrdersNewOrderRoute = AppOrdersNewOrderRouteImport.update({
  id: '/orders/new-order',
  path: '/orders/new-order',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppBudgetsNewBudgetRoute = AppBudgetsNewBudgetRouteImport.update({
  id: '/budgets/new-budget',
  path: '/budgets/new-budget',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppSystemSyncStatusIndexRoute =
  AppSystemSyncStatusIndexRouteImport.update({
    id: '/system/sync-status/',
    path: '/system/sync-status/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppStockProductStockIndexRoute =
  AppStockProductStockIndexRouteImport.update({
    id: '/stock/product-stock/',
    path: '/stock/product-stock/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppStockEsli011IndexRoute = AppStockEsli011IndexRouteImport.update({
  id: '/stock/esli011/',
  path: '/stock/esli011/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppRegistrationsSalesGroupIndexRoute =
  AppRegistrationsSalesGroupIndexRouteImport.update({
    id: '/registrations/sales-group/',
    path: '/registrations/sales-group/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppOrdersOrderIdIndexRoute = AppOrdersOrderIdIndexRouteImport.update({
  id: '/orders/$orderId/',
  path: '/orders/$orderId/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppAdminUserGroupsIndexRoute = AppAdminUserGroupsIndexRouteImport.update({
  id: '/admin/user-groups/',
  path: '/admin/user-groups/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppAdminSettingsIndexRoute = AppAdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppRegistrationsSalesGroupNewGroupRoute =
  AppRegistrationsSalesGroupNewGroupRouteImport.update({
    id: '/registrations/sales-group/new-group',
    path: '/registrations/sales-group/new-group',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppAdminUsersNewUserRoute = AppAdminUsersNewUserRouteImport.update({
  id: '/admin/users/new-user',
  path: '/admin/users/new-user',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppAdminUserGroupsNewGroupRoute =
  AppAdminUserGroupsNewGroupRouteImport.update({
    id: '/admin/user-groups/new-group',
    path: '/admin/user-groups/new-group',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppRegistrationsSalesGroupGroupIdIndexRoute =
  AppRegistrationsSalesGroupGroupIdIndexRouteImport.update({
    id: '/registrations/sales-group/$groupId/',
    path: '/registrations/sales-group/$groupId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppAdminUserGroupsGroupIdIndexRoute =
  AppAdminUserGroupsGroupIdIndexRouteImport.update({
    id: '/admin/user-groups/$groupId/',
    path: '/admin/user-groups/$groupId/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/budgets/new-budget': typeof AppBudgetsNewBudgetRoute
  '/orders/new-order': typeof AppOrdersNewOrderRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/outlet': typeof AppOutletIndexRoute
  '/admin/user-groups/new-group': typeof AppAdminUserGroupsNewGroupRoute
  '/admin/users/new-user': typeof AppAdminUsersNewUserRoute
  '/registrations/sales-group/new-group': typeof AppRegistrationsSalesGroupNewGroupRoute
  '/admin/settings': typeof AppAdminSettingsIndexRoute
  '/admin/user-groups': typeof AppAdminUserGroupsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/orders/$orderId': typeof AppOrdersOrderIdIndexRoute
  '/registrations/sales-group': typeof AppRegistrationsSalesGroupIndexRoute
  '/stock/esli011': typeof AppStockEsli011IndexRoute
  '/stock/product-stock': typeof AppStockProductStockIndexRoute
  '/system/sync-status': typeof AppSystemSyncStatusIndexRoute
  '/admin/user-groups/$groupId': typeof AppAdminUserGroupsGroupIdIndexRoute
  '/registrations/sales-group/$groupId': typeof AppRegistrationsSalesGroupGroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/budgets/new-budget': typeof AppBudgetsNewBudgetRoute
  '/orders/new-order': typeof AppOrdersNewOrderRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/outlet': typeof AppOutletIndexRoute
  '/admin/user-groups/new-group': typeof AppAdminUserGroupsNewGroupRoute
  '/admin/users/new-user': typeof AppAdminUsersNewUserRoute
  '/registrations/sales-group/new-group': typeof AppRegistrationsSalesGroupNewGroupRoute
  '/admin/settings': typeof AppAdminSettingsIndexRoute
  '/admin/user-groups': typeof AppAdminUserGroupsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/orders/$orderId': typeof AppOrdersOrderIdIndexRoute
  '/registrations/sales-group': typeof AppRegistrationsSalesGroupIndexRoute
  '/stock/esli011': typeof AppStockEsli011IndexRoute
  '/stock/product-stock': typeof AppStockProductStockIndexRoute
  '/system/sync-status': typeof AppSystemSyncStatusIndexRoute
  '/admin/user-groups/$groupId': typeof AppAdminUserGroupsGroupIdIndexRoute
  '/registrations/sales-group/$groupId': typeof AppRegistrationsSalesGroupGroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/budgets/new-budget': typeof AppBudgetsNewBudgetRoute
  '/_app/orders/new-order': typeof AppOrdersNewOrderRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/outlet/': typeof AppOutletIndexRoute
  '/_app/admin/user-groups/new-group': typeof AppAdminUserGroupsNewGroupRoute
  '/_app/admin/users/new-user': typeof AppAdminUsersNewUserRoute
  '/_app/registrations/sales-group/new-group': typeof AppRegistrationsSalesGroupNewGroupRoute
  '/_app/admin/settings/': typeof AppAdminSettingsIndexRoute
  '/_app/admin/user-groups/': typeof AppAdminUserGroupsIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/orders/$orderId/': typeof AppOrdersOrderIdIndexRoute
  '/_app/registrations/sales-group/': typeof AppRegistrationsSalesGroupIndexRoute
  '/_app/stock/esli011/': typeof AppStockEsli011IndexRoute
  '/_app/stock/product-stock/': typeof AppStockProductStockIndexRoute
  '/_app/system/sync-status/': typeof AppSystemSyncStatusIndexRoute
  '/_app/admin/user-groups/$groupId/': typeof AppAdminUserGroupsGroupIdIndexRoute
  '/_app/registrations/sales-group/$groupId/': typeof AppRegistrationsSalesGroupGroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/login'
    | '/'
    | '/budgets/new-budget'
    | '/orders/new-order'
    | '/dashboard'
    | '/orders'
    | '/outlet'
    | '/admin/user-groups/new-group'
    | '/admin/users/new-user'
    | '/registrations/sales-group/new-group'
    | '/admin/settings'
    | '/admin/user-groups'
    | '/admin/users'
    | '/orders/$orderId'
    | '/registrations/sales-group'
    | '/stock/esli011'
    | '/stock/product-stock'
    | '/system/sync-status'
    | '/admin/user-groups/$groupId'
    | '/registrations/sales-group/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/login'
    | '/'
    | '/budgets/new-budget'
    | '/orders/new-order'
    | '/dashboard'
    | '/orders'
    | '/outlet'
    | '/admin/user-groups/new-group'
    | '/admin/users/new-user'
    | '/registrations/sales-group/new-group'
    | '/admin/settings'
    | '/admin/user-groups'
    | '/admin/users'
    | '/orders/$orderId'
    | '/registrations/sales-group'
    | '/stock/esli011'
    | '/stock/product-stock'
    | '/system/sync-status'
    | '/admin/user-groups/$groupId'
    | '/registrations/sales-group/$groupId'
  id:
    | '__root__'
    | '/_app'
    | '/auth/login'
    | '/_app/'
    | '/_app/budgets/new-budget'
    | '/_app/orders/new-order'
    | '/_app/dashboard/'
    | '/_app/orders/'
    | '/_app/outlet/'
    | '/_app/admin/user-groups/new-group'
    | '/_app/admin/users/new-user'
    | '/_app/registrations/sales-group/new-group'
    | '/_app/admin/settings/'
    | '/_app/admin/user-groups/'
    | '/_app/admin/users/'
    | '/_app/orders/$orderId/'
    | '/_app/registrations/sales-group/'
    | '/_app/stock/esli011/'
    | '/_app/stock/product-stock/'
    | '/_app/system/sync-status/'
    | '/_app/admin/user-groups/$groupId/'
    | '/_app/registrations/sales-group/$groupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/outlet/': {
      id: '/_app/outlet/'
      path: '/outlet'
      fullPath: '/outlet'
      preLoaderRoute: typeof AppOutletIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/orders/new-order': {
      id: '/_app/orders/new-order'
      path: '/orders/new-order'
      fullPath: '/orders/new-order'
      preLoaderRoute: typeof AppOrdersNewOrderRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/budgets/new-budget': {
      id: '/_app/budgets/new-budget'
      path: '/budgets/new-budget'
      fullPath: '/budgets/new-budget'
      preLoaderRoute: typeof AppBudgetsNewBudgetRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/system/sync-status/': {
      id: '/_app/system/sync-status/'
      path: '/system/sync-status'
      fullPath: '/system/sync-status'
      preLoaderRoute: typeof AppSystemSyncStatusIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/stock/product-stock/': {
      id: '/_app/stock/product-stock/'
      path: '/stock/product-stock'
      fullPath: '/stock/product-stock'
      preLoaderRoute: typeof AppStockProductStockIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/stock/esli011/': {
      id: '/_app/stock/esli011/'
      path: '/stock/esli011'
      fullPath: '/stock/esli011'
      preLoaderRoute: typeof AppStockEsli011IndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/sales-group/': {
      id: '/_app/registrations/sales-group/'
      path: '/registrations/sales-group'
      fullPath: '/registrations/sales-group'
      preLoaderRoute: typeof AppRegistrationsSalesGroupIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/orders/$orderId/': {
      id: '/_app/orders/$orderId/'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/admin/user-groups/': {
      id: '/_app/admin/user-groups/'
      path: '/admin/user-groups'
      fullPath: '/admin/user-groups'
      preLoaderRoute: typeof AppAdminUserGroupsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/admin/settings/': {
      id: '/_app/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/sales-group/new-group': {
      id: '/_app/registrations/sales-group/new-group'
      path: '/registrations/sales-group/new-group'
      fullPath: '/registrations/sales-group/new-group'
      preLoaderRoute: typeof AppRegistrationsSalesGroupNewGroupRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/admin/users/new-user': {
      id: '/_app/admin/users/new-user'
      path: '/admin/users/new-user'
      fullPath: '/admin/users/new-user'
      preLoaderRoute: typeof AppAdminUsersNewUserRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/admin/user-groups/new-group': {
      id: '/_app/admin/user-groups/new-group'
      path: '/admin/user-groups/new-group'
      fullPath: '/admin/user-groups/new-group'
      preLoaderRoute: typeof AppAdminUserGroupsNewGroupRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/registrations/sales-group/$groupId/': {
      id: '/_app/registrations/sales-group/$groupId/'
      path: '/registrations/sales-group/$groupId'
      fullPath: '/registrations/sales-group/$groupId'
      preLoaderRoute: typeof AppRegistrationsSalesGroupGroupIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/_app/admin/user-groups/$groupId/': {
      id: '/_app/admin/user-groups/$groupId/'
      path: '/admin/user-groups/$groupId'
      fullPath: '/admin/user-groups/$groupId'
      preLoaderRoute: typeof AppAdminUserGroupsGroupIdIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppBudgetsNewBudgetRoute: typeof AppBudgetsNewBudgetRoute
  AppOrdersNewOrderRoute: typeof AppOrdersNewOrderRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppOutletIndexRoute: typeof AppOutletIndexRoute
  AppAdminUserGroupsNewGroupRoute: typeof AppAdminUserGroupsNewGroupRoute
  AppAdminUsersNewUserRoute: typeof AppAdminUsersNewUserRoute
  AppRegistrationsSalesGroupNewGroupRoute: typeof AppRegistrationsSalesGroupNewGroupRoute
  AppAdminSettingsIndexRoute: typeof AppAdminSettingsIndexRoute
  AppAdminUserGroupsIndexRoute: typeof AppAdminUserGroupsIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
  AppOrdersOrderIdIndexRoute: typeof AppOrdersOrderIdIndexRoute
  AppRegistrationsSalesGroupIndexRoute: typeof AppRegistrationsSalesGroupIndexRoute
  AppStockEsli011IndexRoute: typeof AppStockEsli011IndexRoute
  AppStockProductStockIndexRoute: typeof AppStockProductStockIndexRoute
  AppSystemSyncStatusIndexRoute: typeof AppSystemSyncStatusIndexRoute
  AppAdminUserGroupsGroupIdIndexRoute: typeof AppAdminUserGroupsGroupIdIndexRoute
  AppRegistrationsSalesGroupGroupIdIndexRoute: typeof AppRegistrationsSalesGroupGroupIdIndexRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppBudgetsNewBudgetRoute: AppBudgetsNewBudgetRoute,
  AppOrdersNewOrderRoute: AppOrdersNewOrderRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppOutletIndexRoute: AppOutletIndexRoute,
  AppAdminUserGroupsNewGroupRoute: AppAdminUserGroupsNewGroupRoute,
  AppAdminUsersNewUserRoute: AppAdminUsersNewUserRoute,
  AppRegistrationsSalesGroupNewGroupRoute:
    AppRegistrationsSalesGroupNewGroupRoute,
  AppAdminSettingsIndexRoute: AppAdminSettingsIndexRoute,
  AppAdminUserGroupsIndexRoute: AppAdminUserGroupsIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
  AppOrdersOrderIdIndexRoute: AppOrdersOrderIdIndexRoute,
  AppRegistrationsSalesGroupIndexRoute: AppRegistrationsSalesGroupIndexRoute,
  AppStockEsli011IndexRoute: AppStockEsli011IndexRoute,
  AppStockProductStockIndexRoute: AppStockProductStockIndexRoute,
  AppSystemSyncStatusIndexRoute: AppSystemSyncStatusIndexRoute,
  AppAdminUserGroupsGroupIdIndexRoute: AppAdminUserGroupsGroupIdIndexRoute,
  AppRegistrationsSalesGroupGroupIdIndexRoute:
    AppRegistrationsSalesGroupGroupIdIndexRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
